name: Docker images build and publish

on:
  push:
    branches:
      - master
      - deploy
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

env:
  # Build for default OS, linux, and common CPU architectures
  # Reference https://github.com/docker/setup-buildx-action#quick-start
  TPLATFORMS: linux/amd64,linux/arm64,linux/arm,linux/386

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: vbphung
          password: ${{ secrets.DOCKER_PWD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: ./.github/workflows/Dockerfile
          context: .
          platforms: ${{ env.TPLATFORMS }}
          push: true
          tags: vbphung/btcd:latest
